const {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, BorderStyle, ShadingType,
} = require("docx");
const fs = require("fs");

// ─── Helpers ─────────────────────────────────────────────────────────────────

function titulo(text) {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 400, after: 200 },
  });
}

function subtitulo(text) {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 300, after: 120 },
  });
}

function paragrafo(text) {
  return new Paragraph({
    children: [new TextRun({ text, size: 22 })],
    spacing: { after: 160 },
  });
}

function negrito(text) {
  return new Paragraph({
    children: [new TextRun({ text, bold: true, size: 22 })],
    spacing: { after: 100 },
  });
}

function bullet(text) {
  return new Paragraph({
    children: [new TextRun({ text: `• ${text}`, size: 22 })],
    indent: { left: 360 },
    spacing: { after: 80 },
  });
}

function codigo(text) {
  return new Paragraph({
    children: [new TextRun({ text, font: "Courier New", size: 18 })],
    indent: { left: 360 },
    spacing: { after: 60 },
    shading: { type: ShadingType.CLEAR, fill: "F0F0F0" },
  });
}

function blocoCode(lines) {
  return lines.map(l => codigo(l));
}

function separador() {
  return new Paragraph({
    children: [new TextRun({ text: "─────────────────────────────────────────────────────────────────", size: 18, color: "CCCCCC" })],
    spacing: { before: 200, after: 200 },
  });
}

function espaco() {
  return new Paragraph({ text: "", spacing: { after: 120 } });
}

// ─── Documento ───────────────────────────────────────────────────────────────

const sections = [];

// CAPA
sections.push(
  new Paragraph({
    children: [new TextRun({ text: "Trecos3D", bold: true, size: 64, color: "9810FA" })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 1200, after: 200 },
  }),
  new Paragraph({
    children: [new TextRun({ text: "Documentação Técnica Completa do Projeto", size: 30, italics: true })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
  }),
  new Paragraph({
    children: [new TextRun({ text: "Aplicativo de Loja Virtual de Impressão 3D", size: 24 })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
  }),
  new Paragraph({
    children: [new TextRun({ text: "Versão 1.0  —  2025", size: 22 })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 800 },
  }),
  separador(),
);

// ÍNDICE
sections.push(
  titulo("Sumário"),
  paragrafo("1. Visão Geral do Projeto"),
  paragrafo("2. Tecnologias e Bibliotecas Utilizadas"),
  paragrafo("3. Estrutura de Pastas"),
  paragrafo("4. Banco de Dados (Supabase / PostgreSQL)"),
  paragrafo("5. Backend — server.js (Node.js + Express)"),
  paragrafo("6. Contextos Globais (AuthContext, CartContext, ThemeContext)"),
  paragrafo("7. Serviço de API — authService.ts"),
  paragrafo("8. Tela: Login"),
  paragrafo("9. Tela: Cadastro (Register)"),
  paragrafo("10. Tela: Home (Loja)"),
  paragrafo("11. Tela: Carrinho"),
  paragrafo("12. Tela: Meus Pedidos"),
  paragrafo("13. Tela: Detalhes do Pedido"),
  paragrafo("14. Tela: Novo Orçamento"),
  paragrafo("15. Tela: Meus Orçamentos"),
  paragrafo("16. Tela: Perfil do Usuário"),
  paragrafo("17. Painel Admin — Dashboard"),
  paragrafo("18. Painel Admin — Produtos"),
  paragrafo("19. Painel Admin — Orçamentos"),
  paragrafo("20. Painel Admin — Pedidos"),
  paragrafo("21. Navegação (Expo Router e Layouts)"),
  paragrafo("22. Fluxos Completos do Usuário"),
  paragrafo("23. Segurança"),
  separador(),
);

// 1. VISÃO GERAL
sections.push(
  titulo("1. Visão Geral do Projeto"),
  paragrafo("O Trecos3D é um aplicativo mobile completo para uma loja de impressão 3D. Por ele, um cliente pode:"),
  bullet("Navegar pelo catálogo de produtos prontos (peças já impressas em 3D)"),
  bullet("Adicionar produtos ao carrinho e finalizar pedidos"),
  bullet("Enviar fotos de peças personalizadas e solicitar orçamentos"),
  bullet("Acompanhar o status dos seus pedidos e orçamentos"),
  bullet("Usar modo claro ou escuro no aplicativo"),
  espaco(),
  paragrafo("Do lado do administrador, é possível:"),
  bullet("Ver um painel com faturamento total, pedidos realizados e orçamentos pendentes"),
  bullet("Cadastrar, editar e remover produtos"),
  bullet("Aprovar ou rejeitar orçamentos enviados pelos clientes"),
  bullet("Visualizar todos os pedidos e atualizar seus status"),
  espaco(),
  paragrafo("O projeto é dividido em duas partes principais:"),
  bullet("Frontend: aplicativo React Native construído com Expo, escrito em TypeScript."),
  bullet("Backend: servidor Node.js com Express e banco de dados PostgreSQL hospedado no Supabase."),
  separador(),
);

// 2. TECNOLOGIAS
sections.push(
  titulo("2. Tecnologias e Bibliotecas Utilizadas"),
  subtitulo("2.1 Frontend (Aplicativo)"),

  negrito("React Native"),
  paragrafo("Framework que permite criar aplicativos mobile para Android e iOS usando JavaScript/TypeScript. Em vez de escrever código diferente para cada plataforma, você escreve uma vez e ele funciona nos dois sistemas. É mantido pelo Meta (Facebook)."),

  negrito("Expo (versão 56)"),
  paragrafo("Uma camada que simplifica muito o desenvolvimento com React Native. Com Expo você não precisa configurar Android Studio ou Xcode para testar o app — basta usar o app 'Expo Go' no celular. Expo também fornece diversas bibliotecas prontas (câmera, galeria de fotos, fontes, gradientes, etc.)."),

  negrito("TypeScript"),
  paragrafo("É JavaScript com tipagem. Com TypeScript você declara o tipo de cada variável (por exemplo: 'essa variável é um número', 'esse objeto tem os campos id e nome'). Isso ajuda a encontrar erros antes de rodar o código e torna o projeto muito mais seguro e fácil de entender."),

  negrito("Expo Router"),
  paragrafo("Sistema de navegação baseado em arquivos. Cada arquivo dentro da pasta src/app/ vira automaticamente uma tela. Se você criar o arquivo 'perfil.tsx', automaticamente existe uma rota '/perfil'. Funciona de forma parecida com o Next.js para web."),

  negrito("Axios"),
  paragrafo("Biblioteca para fazer requisições HTTP (chamadas para a API). É como um mensageiro: você diz 'vá buscar os produtos no servidor' e o Axios vai, pega a resposta, e traz de volta para o aplicativo. Muito mais conveniente do que usar o fetch nativo do JavaScript pois tem tratamento de erro melhor, interceptors e outras funcionalidades."),

  negrito("@react-native-async-storage/async-storage"),
  paragrafo("Funciona como um 'baú de armazenamento' no celular. Você pode guardar informações que precisam persistir mesmo quando o app é fechado — como o token JWT do usuário logado. Funciona de forma parecida com o localStorage do navegador web, mas para aplicativos mobile."),

  negrito("expo-image-picker"),
  paragrafo("Biblioteca oficial do Expo para abrir a galeria de fotos do celular ou a câmera. Usada na tela de 'Novo Orçamento', onde o cliente tira ou escolhe uma foto da peça que quer imprimir."),

  negrito("expo-linear-gradient"),
  paragrafo("Permite criar fundos com degradê (gradiente de cores). Usada no cabeçalho da tela Home e no banner de orçamento — cria aquele efeito visual de roxo passando para rosa."),

  negrito("@expo/vector-icons (Ionicons)"),
  paragrafo("Conjunto de ícones vetoriais. O projeto usa a família 'Ionicons' que tem centenas de ícones prontos (lixeira, casa, carrinho, seta para trás, etc.). Ícones vetoriais são leves e ficam nítidos em qualquer resolução de tela."),

  negrito("@expo-google-fonts/inter"),
  paragrafo("Fonte tipográfica 'Inter' do Google. É uma fonte moderna e muito legível, usada amplamente em apps e websites. O Expo facilita o carregamento dela com o hook useFonts()."),

  negrito("react-native-safe-area-context"),
  paragrafo("Garante que o conteúdo do app não fique escondido atrás do 'notch' (a franjinha do iPhone), da câmera frontal ou dos botões de navegação do Android. O componente SafeAreaView e o hook useSafeAreaInsets usam essa biblioteca."),

  negrito("expo-status-bar"),
  paragrafo("Controla a barra de status no topo do celular (onde ficam o horário, bateria e sinal). Permite definir se os ícones devem ser brancos ou pretos dependendo do tema (claro/escuro) do app."),

  espaco(),
  subtitulo("2.2 Backend (Servidor)"),

  negrito("Node.js"),
  paragrafo("Ambiente de execução JavaScript no servidor. Antes do Node.js, JavaScript só rodava no navegador. Com Node.js, você usa a mesma linguagem tanto no app quanto no servidor, o que simplifica muito o desenvolvimento."),

  negrito("Express 5"),
  paragrafo("Framework minimalista para criar servidores HTTP com Node.js. Com Express, você define rotas — por exemplo: 'quando alguém chamar GET /products, busque os produtos no banco'. É a base do servidor do Trecos3D."),

  negrito("PostgreSQL"),
  paragrafo("Banco de dados relacional robusto e gratuito. Os dados do Trecos3D (usuários, produtos, pedidos, orçamentos) são armazenados em tabelas PostgreSQL hospedadas no Supabase."),

  negrito("Supabase"),
  paragrafo("Plataforma que fornece PostgreSQL na nuvem de graça, além de um sistema de armazenamento de arquivos (Storage) usado para guardar as fotos dos orçamentos. O Supabase também fornece uma chave de API para conexão ao banco."),

  negrito("bcrypt"),
  paragrafo("Biblioteca de criptografia. Nunca devemos guardar a senha do usuário como texto simples no banco de dados. O bcrypt transforma a senha em um código embaralhado irreversível — mesmo que o banco seja comprometido, ninguém consegue descobrir a senha original."),

  negrito("jsonwebtoken (JWT)"),
  paragrafo("Biblioteca para criar e verificar tokens JWT. Quando o usuário faz login, o servidor gera um 'crachá digital' (token) que identifica aquele usuário. Esse crachá é enviado em todas as requisições seguintes para provar a identidade do usuário sem precisar fazer login a cada chamada."),

  negrito("multer"),
  paragrafo("Middleware para receber arquivos no servidor. Quando o cliente envia uma foto de orçamento, o Express sozinho não consegue processar arquivos binários — o multer faz esse trabalho, recebendo a imagem e deixando-a disponível em req.file."),

  negrito("dotenv"),
  paragrafo("Carrega variáveis de ambiente do arquivo .env. Permite guardar informações sensíveis (senha do banco, chave JWT, URL do Supabase) fora do código-fonte, evitando que esses dados sejam acidentalmente publicados no GitHub."),

  negrito("cors"),
  paragrafo("Middleware que permite que o app mobile faça requisições ao servidor. Sem o CORS configurado, as chamadas seriam bloqueadas por questões de segurança do navegador."),

  separador(),
);

// 3. ESTRUTURA DE PASTAS
sections.push(
  titulo("3. Estrutura de Pastas"),
  paragrafo("O projeto está dividido em duas grandes partes na raiz:"),
  espaco(),
  ...blocoCode([
    "Trecos3D/",
    "├── src/                            ← Código do aplicativo (frontend)",
    "│   ├── app/                        ← Telas (cada arquivo = uma rota)",
    "│   │   ├── _layout.tsx             ← Layout raiz: fontes + Providers",
    "│   │   ├── index.tsx               ← Redireciona conforme o login",
    "│   │   ├── login.tsx               ← Tela de Login",
    "│   │   ├── register.tsx            ← Tela de Cadastro",
    "│   │   ├── home-guest.tsx          ← Home para visitantes",
    "│   │   ├── (app)/                  ← Telas do cliente logado",
    "│   │   │   ├── _layout.tsx         ← Tab bar: Loja/Carrinho/Pedidos/Perfil",
    "│   │   │   ├── home.tsx            ← Catálogo de produtos",
    "│   │   │   ├── carrinho.tsx        ← Carrinho de compras",
    "│   │   │   ├── meus-pedidos.tsx    ← Lista de pedidos",
    "│   │   │   └── perfil.tsx          ← Perfil e configurações",
    "│   │   ├── (admin)/                ← Telas do administrador",
    "│   │   │   ├── _layout.tsx         ← Tab bar do admin",
    "│   │   │   ├── dashboard.tsx       ← Painel com métricas",
    "│   │   │   ├── produtos.tsx        ← CRUD de produtos",
    "│   │   │   ├── orcamentos.tsx      ← Gerenciar orçamentos",
    "│   │   │   ├── pedidos.tsx         ← Ver todos os pedidos",
    "│   │   │   └── perfil.tsx          ← Perfil do admin",
    "│   │   └── (screens)/              ← Telas sem tab bar",
    "│   │       ├── novo-orcamento.tsx  ← Formulário de orçamento",
    "│   │       ├── meus-orcamentos.tsx ← Lista de orçamentos do cliente",
    "│   │       └── detalhes-pedido.tsx ← Detalhes de um pedido",
    "│   ├── context/                    ← Estado global compartilhado",
    "│   │   ├── AuthContext.tsx         ← Usuário logado e token JWT",
    "│   │   ├── CartContext.tsx         ← Itens no carrinho",
    "│   │   └── ThemeContext.tsx        ← Modo claro/escuro",
    "│   ├── services/",
    "│   │   └── authService.ts          ← Axios com token automático",
    "│   └── config/",
    "│       └── api.ts                  ← URL base da API",
    "│",
    "├── api-impressao-3d/               ← Código do servidor (backend)",
    "│   └── src/",
    "│       ├── server.js               ← Todas as rotas da API",
    "│       ├── db.js                   ← Conexão com o PostgreSQL",
    "│       └── middlewares/",
    "│           └── auth.js             ← verificarToken e verificarAdmin",
    "│",
    "├── app.json                        ← Config do Expo (nome, ícone)",
    "└── package.json                    ← Dependências do projeto",
  ]),
  separador(),
);

// 4. BANCO DE DADOS
sections.push(
  titulo("4. Banco de Dados (Supabase / PostgreSQL)"),
  paragrafo("O banco de dados é hospedado no Supabase e possui 5 tabelas principais:"),
  espaco(),

  subtitulo("Tabela: users"),
  paragrafo("Armazena todos os usuários cadastrados no sistema."),
  ...blocoCode([
    "users",
    "  id             SERIAL PRIMARY KEY    ← Número único gerado automaticamente",
    "  name           VARCHAR(100)          ← Nome do usuário",
    "  email          VARCHAR(150) UNIQUE   ← Email (único, não pode repetir)",
    "  password_hash  TEXT                  ← Senha criptografada com bcrypt",
    "  role           VARCHAR(20)           ← 'user', 'admin' ou 'superadmin'",
    "  phone          VARCHAR(20)           ← Telefone/WhatsApp",
    "  created_at     TIMESTAMP             ← Data e hora de criação",
  ]),
  espaco(),

  subtitulo("Tabela: products"),
  paragrafo("Armazena os produtos da loja (peças 3D já prontas)."),
  ...blocoCode([
    "products",
    "  id           SERIAL PRIMARY KEY",
    "  title        VARCHAR(200)     ← Nome do produto",
    "  description  TEXT             ← Descrição",
    "  price        NUMERIC(10,2)    ← Preço em reais",
    "  stock        INTEGER          ← Quantidade em estoque",
    "  image_url    TEXT             ← URL da imagem",
    "  category     VARCHAR(50)      ← Categoria (Brinquedos, Utilitários, etc.)",
    "  created_at   TIMESTAMP",
  ]),
  espaco(),

  subtitulo("Tabela: quotes (Orçamentos)"),
  paragrafo("Armazena os pedidos de orçamento enviados pelos clientes."),
  ...blocoCode([
    "quotes",
    "  id               SERIAL PRIMARY KEY",
    "  user_id          INTEGER           ← Referência ao usuário que enviou",
    "  file_url         TEXT              ← URL da foto no Supabase Storage",
    "  material         VARCHAR(10)       ← 'PLA', 'ABS' ou 'PETG'",
    "  estimated_grams  NUMERIC           ← Peso estimado em gramas",
    "  calculated_price NUMERIC(10,2)     ← Preço calculado automaticamente",
    "  tamanho          VARCHAR(20)       ← 'Pequeno', 'Médio' ou 'Grande'",
    "  phone            VARCHAR(20)       ← WhatsApp de contato",
    "  status           VARCHAR(20)       ← 'pending', 'approved', 'rejected'",
    "  created_at       TIMESTAMP",
  ]),
  espaco(),

  subtitulo("Tabela: orders (Pedidos)"),
  paragrafo("Armazena os pedidos finalizados na loja."),
  ...blocoCode([
    "orders",
    "  id              SERIAL PRIMARY KEY",
    "  user_id         INTEGER           ← Quem fez o pedido",
    "  quote_id        INTEGER NULL      ← Orçamento vinculado (opcional)",
    "  total_value     NUMERIC(10,2)     ← Valor total (com desconto se aplicável)",
    "  item_count      INTEGER           ← Quantidade de itens",
    "  status          VARCHAR(20)       ← 'pending', 'preparing', 'completed', 'cancelled'",
    "  created_at      TIMESTAMP",
  ]),
  espaco(),

  subtitulo("Tabela: order_items (Itens do Pedido)"),
  paragrafo("Guarda os produtos individuais de cada pedido."),
  ...blocoCode([
    "order_items",
    "  id             SERIAL PRIMARY KEY",
    "  order_id       INTEGER           ← A qual pedido pertence",
    "  product_title  VARCHAR(200)      ← Nome do produto (registrado no momento da compra)",
    "  quantity       INTEGER           ← Quantidade",
    "  unit_price     NUMERIC(10,2)     ← Preço unitário no momento da compra",
  ]),
  espaco(),
  paragrafo("Observação importante: os itens do pedido guardam o nome e preço do produto no momento da compra, não apenas uma referência (ID) ao produto. Isso significa que mesmo que o produto seja editado ou removido depois, o histórico do pedido continua correto e fiel ao que foi comprado."),
  separador(),
);

// 5. BACKEND
sections.push(
  titulo("5. Backend — server.js (Node.js + Express)"),
  paragrafo("O arquivo server.js é o coração do servidor. Ele define todas as rotas (endpoints) que o aplicativo usa para buscar ou enviar dados."),
  espaco(),

  subtitulo("5.1 Configuração inicial"),
  ...blocoCode([
    "const express = require('express');",
    "const cors = require('cors');",
    "const bcrypt = require('bcrypt');",
    "require('dotenv').config();           // carrega o .env",
    "const db = require('./db');           // conexão com o banco",
    "const jwt = require('jsonwebtoken');",
    "const app = express();",
    "const { verificarToken, verificarAdmin } = require('./middlewares/auth');",
    "app.use(express.json());              // recebe dados JSON",
    "app.use(cors());                      // libera CORS",
  ]),
  espaco(),

  subtitulo("5.2 Configuração do Multer e Supabase"),
  ...blocoCode([
    "const multer = require('multer');",
    "const { createClient } = require('@supabase/supabase-js');",
    "",
    "// memoryStorage = guarda o arquivo na memória RAM temporariamente",
    "const upload = multer({ storage: multer.memoryStorage() });",
    "",
    "const supabase = createClient(",
    "  process.env.SUPABASE_URL,",
    "  process.env.SUPABASE_KEY",
    ");",
  ]),
  paragrafo("O Multer com memoryStorage guarda a imagem na memória RAM em vez de salvar em disco. Isso é mais eficiente para depois enviar ao Supabase Storage. O cliente Supabase é criado com as credenciais do .env."),
  espaco(),

  subtitulo("5.3 Rota: POST /register — Criar usuário"),
  ...blocoCode([
    "app.post('/register', async (req, res) => {",
    "  const { name, email, password, role } = req.body;",
    "",
    "  // valida campos obrigatórios",
    "  if (!name || !email || !password) {",
    "    return res.status(400).json({ error: 'Faltam dados obrigatórios!' });",
    "  }",
    "",
    "  // criptografa a senha com 10 rodadas de embaralhamento",
    "  const passwordHash = await bcrypt.hash(password, 10);",
    "",
    "  // insere no banco, retorna o usuário criado (sem a senha)",
    "  const result = await db.query(",
    "    'INSERT INTO users (name, email, password_hash, role) VALUES ($1,$2,$3,$4) RETURNING id,name,email,role'",
    "    [name, email, passwordHash, role || 'user']",
    "  );",
    "",
    "  res.status(201).json({ user: result.rows[0] });",
    "",
    "  // erro 23505 = email duplicado no PostgreSQL",
    "  if (error.code === '23505') {",
    "    return res.status(400).json({ error: 'Este e-mail já pertence a outro usuário.' });",
    "  }",
    "});",
  ]),
  espaco(),

  subtitulo("5.4 Rota: POST /login — Autenticação"),
  ...blocoCode([
    "app.post('/login', async (req, res) => {",
    "  const { email, password } = req.body;",
    "",
    "  // busca o usuário pelo email",
    "  const userResult = await db.query('SELECT * FROM users WHERE email = $1', [email]);",
    "  const user = userResult.rows[0];",
    "",
    "  // compara a senha digitada com o hash salvo no banco",
    "  const isValid = await bcrypt.compare(password, user.password_hash);",
    "  if (!isValid) return res.status(401).json({ error: 'Senha incorreta!' });",
    "",
    "  // cria o token JWT com ID e role do usuário, válido por 7 dias",
    "  const token = jwt.sign(",
    "    { userId: user.id, role: user.role },",
    "    process.env.JWT_SECRET,",
    "    { expiresIn: '7d' }",
    "  );",
    "",
    "  res.json({ user: { id, name, email, role }, token });",
    "});",
  ]),
  espaco(),

  subtitulo("5.5 Rota: POST /orcamentos — Enviar orçamento com foto"),
  ...blocoCode([
    "// upload.single('file') = Multer recebe um arquivo chamado 'file'",
    "app.post('/orcamentos', upload.single('file'), async (req, res) => {",
    "  const { material, estimated_grams, calculated_price, user_id } = req.body;",
    "  const file = req.file;   // imagem recebida pelo Multer",
    "",
    "  // cria nome único: ID_usuario + timestamp + nome original",
    "  const nomeArquivo = `${user_id}_${Date.now()}_${file.originalname}`;",
    "",
    "  // faz upload da imagem para o Supabase Storage",
    "  await supabase.storage.from('orcamentos').upload(",
    "    nomeArquivo, file.buffer, { contentType: file.mimetype }",
    "  );",
    "",
    "  // pega a URL pública da imagem",
    "  const { data } = supabase.storage.from('orcamentos').getPublicUrl(nomeArquivo);",
    "  const publicUrl = data.publicUrl;",
    "",
    "  // salva os dados do orçamento no banco com a URL da foto",
    "  await db.query(",
    "    'INSERT INTO quotes (user_id, file_url, material, ...) VALUES ($1, $2, ...) RETURNING *'",
    "  );",
    "});",
  ]),
  espaco(),

  subtitulo("5.6 Rota: POST /orders — Criar pedido com desconto"),
  ...blocoCode([
    "app.post('/orders', verificarToken, async (req, res) => {",
    "  const { total_value, item_count, items } = req.body;",
    "",
    "  // regra de negócio: 10% de desconto para 10+ itens",
    "  let valorFinal = total_value;",
    "  if (item_count >= 10) {",
    "    valorFinal = total_value * 0.90;",
    "  }",
    "",
    "  // cria o pedido principal",
    "  const orderResult = await db.query(",
    "    'INSERT INTO orders (user_id, total_value, item_count, status) VALUES ($1,$2,$3,\\'preparing\\') RETURNING *'",
    "    [req.userId, valorFinal, item_count]   // req.userId vem do middleware JWT",
    "  );",
    "",
    "  const orderId = orderResult.rows[0].id;",
    "",
    "  // salva cada item individualmente em order_items",
    "  for (const item of items) {",
    "    await db.query(",
    "      'INSERT INTO order_items (order_id, product_title, quantity, unit_price) VALUES ($1,$2,$3,$4)'",
    "      [orderId, item.product_title, item.quantity, item.unit_price]",
    "    );",
    "  }",
    "});",
  ]),
  espaco(),

  subtitulo("5.7 Middlewares de Segurança (auth.js)"),
  ...blocoCode([
    "function verificarToken(req, res, next) {",
    "  // pega o token do cabeçalho da requisição",
    "  const authHeader = req.headers['authorization'];",
    "  const token = authHeader && authHeader.split(' ')[1]; // 'Bearer TOKEN'",
    "",
    "  if (!token) return res.status(401).json({ error: 'Token não enviado.' });",
    "",
    "  jwt.verify(token, process.env.JWT_SECRET, (err, decoded) => {",
    "    if (err) return res.status(403).json({ error: 'Token inválido.' });",
    "    req.userId = decoded.userId;  // disponibiliza o ID do usuário",
    "    req.userRole = decoded.role;  // disponibiliza o role",
    "    next(); // permite que a rota continue executando",
    "  });",
    "}",
    "",
    "function verificarAdmin(req, res, next) {",
    "  if (req.userRole !== 'admin' && req.userRole !== 'superadmin') {",
    "    return res.status(403).json({ error: 'Acesso negado.' });",
    "  }",
    "  next();",
    "}",
  ]),
  paragrafo("Middleware é uma função que roda no meio do caminho de uma requisição. Para uma rota como app.get('/dashboard', verificarToken, verificarAdmin, handler), o Express executa: 1) verificarToken, 2) verificarAdmin, 3) o handler final. Se qualquer middleware chamar res.status(403).json(...) ao invés de next(), a cadeia para e o handler não é executado."),

  separador(),
);

// 6. CONTEXTOS
sections.push(
  titulo("6. Contextos Globais"),
  paragrafo("Contextos são a forma do React de compartilhar informações entre telas sem precisar passar props de componente em componente. Em vez de cada tela buscar o usuário logado novamente, todos compartilham o mesmo estado global."),
  espaco(),

  subtitulo("6.1 AuthContext.tsx — Autenticação"),
  ...blocoCode([
    "export const AuthContext = createContext<AuthContextData>({} as AuthContextData);",
    "",
    "export const AuthProvider = ({ children }) => {",
    "  const [user, setUser] = useState<User | null>(null);",
    "  const [token, setToken] = useState<string | null>(null);",
    "  const [isLoading, setIsLoading] = useState(true);",
    "",
    "  useEffect(() => {",
    "    // ao abrir o app, tenta recuperar a sessão salva",
    "    async function loadStorageData() {",
    "      const storedUser = await AsyncStorage.getItem('@Trecos3D:user');",
    "      const storedToken = await AsyncStorage.getItem('@Trecos3D:token');",
    "      if (storedUser && storedToken) {",
    "        setUser(JSON.parse(storedUser));",
    "        setToken(storedToken);",
    "      }",
    "      setIsLoading(false);",
    "    }",
    "    loadStorageData();",
    "  }, []);",
    "",
    "  const signIn = async (userData, token) => {",
    "    await AsyncStorage.setItem('@Trecos3D:user', JSON.stringify(userData));",
    "    await AsyncStorage.setItem('@Trecos3D:token', token);",
    "    setUser(userData);",
    "    setToken(token);",
    "  };",
    "",
    "  const signOut = async () => {",
    "    await AsyncStorage.removeItem('@Trecos3D:user');",
    "    await AsyncStorage.removeItem('@Trecos3D:token');",
    "    setUser(null);",
    "    setToken(null);",
    "  };",
    "};",
  ]),
  bullet("Quando o app é aberto, o useEffect() tenta recuperar o usuário e token do AsyncStorage"),
  bullet("Se encontrar dados válidos, o usuário já fica logado automaticamente"),
  bullet("isLoading fica como true enquanto carrega — as telas esperam antes de redirecionar"),
  bullet("signIn salva no AsyncStorage E atualiza o estado React (ambos os lugares)"),
  bullet("signOut limpa os dois lugares simultaneamente"),
  espaco(),

  subtitulo("6.2 CartContext.tsx — Carrinho de Compras"),
  ...blocoCode([
    "export function CartProvider({ children }) {",
    "  const [carrinho, setCarrinho] = useState<ProdutoCarrinho[]>([]);",
    "",
    "  function adicionarAoCarrinho(produto) {",
    "    const itemExistente = carrinho.find(item => item.id === produto.id);",
    "    if (itemExistente) {",
    "      // produto já está no carrinho → aumenta quantidade",
    "      setCarrinho(carrinho.map(item =>",
    "        item.id === produto.id",
    "          ? { ...item, quantidade: item.quantidade + 1 }",
    "          : item",
    "      ));",
    "    } else {",
    "      // produto novo → adiciona com quantidade 1",
    "      setCarrinho([...carrinho, { ...produto, quantidade: 1 }]);",
    "    }",
    "  }",
    "",
    "  function removerDoCarrinho(id) {",
    "    // cria nova lista sem o item com esse id",
    "    setCarrinho(carrinho.filter(item => item.id !== id));",
    "  }",
    "",
    "  function diminuirQuantidade(id) {",
    "    setCarrinho(",
    "      carrinho",
    "        .map(item => item.id === id",
    "          ? { ...item, quantidade: item.quantidade - 1 }",
    "          : item",
    "        )",
    "        .filter(item => item.quantidade > 0) // remove se chegar a 0",
    "    );",
    "  }",
    "",
    "  function limparCarrinho() { setCarrinho([]); }",
    "}",
  ]),
  espaco(),

  subtitulo("6.3 ThemeContext.tsx — Tema Claro/Escuro"),
  ...blocoCode([
    "const lightColors = {",
    "  background: '#F5F5F5', card: '#FFFFFF', text: '#1A1A1A',",
    "  subtext: '#6B7280', border: '#E5E7EB', divider: '#F3F4F6',",
    "  tabBar: '#FFFFFF', placeholder: '#9CA3AF',",
    "};",
    "",
    "const darkColors = {",
    "  background: '#0F0F0F', card: '#1C1C1E', text: '#F9FAFB',",
    "  subtext: '#9CA3AF', border: '#374151', divider: '#1F2937',",
    "  tabBar: '#1C1C1E', placeholder: '#6B7280',",
    "};",
    "",
    "export function ThemeProvider({ children }) {",
    "  const [isDark, setIsDark] = useState(false);",
    "  const colors = isDark ? darkColors : lightColors;",
    "  function toggleTheme() { setIsDark(prev => !prev); }",
    "}",
    "",
    "// uso nas telas:",
    "const { colors, isDark, toggleTheme } = useTheme();",
    "// qualquer estilo usa colors.background em vez de '#F5F5F5'",
  ]),
  paragrafo("O ThemeContext define dois grupos de cores. Qualquer tela que chame useTheme() recebe o objeto 'colors' com as cores certas para o tema atual. Ao mudar o tema, todas as telas atualizam automaticamente porque React re-renderiza os componentes quando o contexto muda."),
  separador(),
);

// 7. AUTH SERVICE
sections.push(
  titulo("7. Serviço de API — authService.ts"),
  ...blocoCode([
    "import axios from 'axios';",
    "import AsyncStorage from '@react-native-async-storage/async-storage';",
    "import { API_BASE_URL } from '../config/api';",
    "",
    "// cria uma instância Axios com URL base configurada",
    "const api = axios.create({",
    "  baseURL: API_BASE_URL,  // ex: http://192.168.0.10:3000",
    "});",
    "",
    "// interceptor: roda ANTES de cada requisição",
    "api.interceptors.request.use(async (config) => {",
    "  const token = await AsyncStorage.getItem('@Trecos3D:token');",
    "  if (token) {",
    "    config.headers.Authorization = `Bearer ${token}`;",
    "    // adiciona o token automaticamente em todas as chamadas",
    "  }",
    "  return config;",
    "});",
    "",
    "export default api;",
  ]),
  paragrafo("Por que isso é útil? Sem esse interceptor, cada tela precisaria buscar o token manualmente e adicionar no header: api.get('/orders', { headers: { Authorization: 'Bearer ' + token } }). Com o interceptor, basta fazer api.get('/orders') — o token é adicionado automaticamente."),
  separador(),
);

// 8. LOGIN
sections.push(
  titulo("8. Tela: Login (login.tsx)"),
  paragrafo("Primeira tela que o usuário vê ao abrir o app sem estar logado. Campos: Email e Senha."),
  espaco(),
  subtitulo("Fluxo da tela de login:"),
  bullet("1. Usuário digita email e senha"),
  bullet("2. Pressiona 'Entrar' — função handleLogin é chamada"),
  bullet("3. O app faz POST /login com email e senha para o servidor"),
  bullet("4. O servidor verifica a senha com bcrypt, cria o token JWT"),
  bullet("5. O app recebe { user, token } na resposta"),
  bullet("6. Chama signIn(userData, token) do AuthContext"),
  bullet("7. signIn salva no AsyncStorage e atualiza o estado"),
  bullet("8. O Expo Router detecta user != null e redireciona automaticamente"),
  bullet("   → usuário normal: /(app)/home"),
  bullet("   → admin/superadmin: /(admin)/dashboard"),
  espaco(),
  paragrafo("O redirecionamento pós-login não precisa ser feito manualmente. O _layout.tsx raiz e os layouts de grupos monitoram o AuthContext: quando o 'user' muda de null para um objeto, o Expo Router redireciona para a tela correta automaticamente."),
  separador(),
);

// 9. CADASTRO
sections.push(
  titulo("9. Tela: Cadastro (register.tsx)"),
  paragrafo("Permite criar uma nova conta de usuário. Campos: Nome, Email, Telefone/WhatsApp, Senha e Confirmação de Senha."),
  espaco(),

  subtitulo("Máscara de telefone em tempo real:"),
  ...blocoCode([
    "function formatarTelefone(valor: string) {",
    "  // remove tudo que não é número, limita a 11 dígitos",
    "  const numeros = valor.replace(/\\D/g, '').slice(0, 11);",
    "",
    "  if (numeros.length <= 2)",
    "    return `(${numeros}`;",
    "  if (numeros.length <= 7)",
    "    return `(${numeros.slice(0,2)}) ${numeros.slice(2)}`;",
    "  if (numeros.length <= 10)",
    "    return `(${numeros.slice(0,2)}) ${numeros.slice(2,6)}-${numeros.slice(6)}`;",
    "  return `(${numeros.slice(0,2)}) ${numeros.slice(2,7)}-${numeros.slice(7)}`;",
    "  // resultado final: (11) 99999-9999",
    "}",
    "",
    "<TextInput",
    "  value={telefone}",
    "  onChangeText={(v) => setTelefone(formatarTelefone(v))}",
    "  keyboardType='phone-pad'",
    "/>",
  ]),
  bullet("replace(/\\D/g, '') é uma expressão regular que remove tudo que não é dígito"),
  bullet("slice(0, 11) limita a 11 caracteres (2 do DDD + 9 do celular)"),
  bullet("A formatação muda conforme a quantidade de dígitos digitados"),
  bullet("keyboardType='phone-pad' abre teclado numérico no celular"),
  espaco(),

  subtitulo("Validações:"),
  bullet("Nome, email, telefone e senha são obrigatórios"),
  bullet("Telefone precisa ter pelo menos 10 dígitos"),
  bullet("Senha e confirmação precisam ser idênticas"),
  bullet("Após cadastrar com sucesso, redireciona para a tela de Login"),
  separador(),
);

// 10. HOME
sections.push(
  titulo("10. Tela: Home / Loja (home.tsx)"),
  paragrafo("Tela principal do cliente. Mostra o catálogo de produtos com busca, filtro por categoria e acesso ao orçamento personalizado."),
  espaco(),

  subtitulo("10.1 Carregar produtos da API"),
  ...blocoCode([
    "async function buscarProdutos() {",
    "  try {",
    "    const response = await api.get('/products');",
    "    setProdutos(response.data);",
    "  } catch (error) {",
    "    // silencioso — a lista ficará vazia",
    "  } finally {",
    "    setCarregando(false); // sempre executa, com erro ou sem",
    "  }",
    "}",
    "",
    "useEffect(() => {",
    "  buscarProdutos();",
    "}, []);  // [] = roda apenas uma vez quando a tela carrega",
  ]),
  espaco(),

  subtitulo("10.2 Filtros de busca e categoria"),
  ...blocoCode([
    "const CATEGORIAS = ['Todos', 'Brinquedos', 'Utilitários', 'Decoração'];",
    "",
    "const produtosFiltrados = produtos.filter(p => {",
    "  const nomeOk = p.title?.toLowerCase().includes(busca.toLowerCase());",
    "  const categoriaOk = categoriaAtiva === 'Todos' || p.category === categoriaAtiva;",
    "  return nomeOk && categoriaOk;",
    "});",
  ]),
  paragrafo("A filtragem acontece no lado do app (client-side), sem nova chamada ao servidor. Isso é mais rápido para o usuário e economiza requisições. A busca ignora maiúsculas/minúsculas com toLowerCase()."),
  espaco(),

  subtitulo("10.3 Banner de orçamento"),
  ...blocoCode([
    "<TouchableOpacity",
    "  onPress={() => router.push('/novo-orcamento')}",
    ">",
    "  <LinearGradient colors={['#9810FA', '#E60076']}>",
    "    <Ionicons name='print-outline' />",
    "    <Text>Tem uma peça para imprimir?</Text>",
    "    <Text>Solicite um orçamento grátis →</Text>",
    "  </LinearGradient>",
    "</TouchableOpacity>",
  ]),
  espaco(),

  subtitulo("10.4 Modal de detalhes do produto"),
  paragrafo("Quando o usuário toca no card do produto, um Modal aparece com informações completas e seleção de material. É uma sobreposição que aparece na frente de tudo sem mudar de tela."),
  ...blocoCode([
    "<Modal",
    "  visible={produtoSelecionado !== null}",
    "  animationType='slide'  // sobe de baixo",
    "  onRequestClose={() => setProdutoSelecionado(null)} // botão voltar Android",
    ">",
    "  {/* Seleção de material: PLA, ABS ou PETG */}",
    "  {['PLA', 'ABS', 'PETG'].map(mat => (",
    "    <TouchableOpacity",
    "      key={mat}",
    "      style={[styles.chip, materialSelecionado === mat && styles.chipAtivo]}",
    "      onPress={() => setMaterialSelecionado(mat)}",
    "    >",
    "      <Text>{mat}</Text>",
    "    </TouchableOpacity>",
    "  ))}",
    "",
    "  {/* Botão de compra no rodapé do modal */}",
    "  <TouchableOpacity onPress={() => {",
    "    adicionarAoCarrinho({ ...produtoSelecionado, material_selecionado: materialSelecionado });",
    "    setProdutoSelecionado(null); // fecha o modal",
    "  }}>",
    "    <Text>Adicionar ao Carrinho</Text>",
    "  </TouchableOpacity>",
    "</Modal>",
  ]),
  separador(),
);

// 11. CARRINHO
sections.push(
  titulo("11. Tela: Carrinho (carrinho.tsx)"),
  paragrafo("Exibe produtos adicionados, permite ajustar quantidades, remover itens e finalizar o pedido."),
  espaco(),

  subtitulo("11.1 Renderizar cada item"),
  ...blocoCode([
    "function renderizarItem({ item }) {",
    "  return (",
    "    <View style={styles.card}>",
    "      {item.image_url ? (",
    "        <Image source={{ uri: item.image_url }} style={styles.imagem} />",
    "      ) : (",
    "        <View style={styles.imagemVazia}>  {/* placeholder cinza */}",
    "          <Ionicons name='cube-outline' />",
    "        </View>",
    "      )}",
    "",
    "      <View style={styles.info}>",
    "        <Text>{item.title}</Text>",
    "        <Text>R$ {Number(item.price).toFixed(2)}</Text>",
    "",
    "        {/* controles de quantidade */}",
    "        <View style={styles.quantidade}>",
    "          {item.quantidade > 1 && (  // botão − só aparece se qtd > 1",
    "            <TouchableOpacity onPress={() => diminuirQuantidade(item.id)}>",
    "              <Ionicons name='remove' />",
    "            </TouchableOpacity>",
    "          )}",
    "          <Text>{item.quantidade}</Text>",
    "          <TouchableOpacity onPress={() => aumentarQuantidade(item.id)}>",
    "            <Ionicons name='add' />",
    "          </TouchableOpacity>",
    "        </View>",
    "      </View>",
    "",
    "      {/* lixeira para remover item */}",
    "      <TouchableOpacity onPress={() => confirmarRemocao(item.id, item.title)}>",
    "        <Ionicons name='trash-outline' color='#EF4444' />",
    "      </TouchableOpacity>",
    "    </View>",
    "  );",
    "}",
  ]),
  espaco(),

  subtitulo("11.2 Calcular total"),
  ...blocoCode([
    "const valorTotal = carrinho.reduce(",
    "  (total, item) => total + (item.price * item.quantidade),",
    "  0   // valor inicial",
    ");",
  ]),
  paragrafo("O método .reduce() percorre todos os itens do array e vai acumulando um valor. Começa com 0 e a cada item soma (preço × quantidade) ao total acumulado."),
  espaco(),

  subtitulo("11.3 Finalizar pedido"),
  ...blocoCode([
    "const finalizarPedido = async () => {",
    "  if (carrinho.length === 0) {",
    "    Alert.alert('Carrinho vazio', 'Adicione produtos antes de finalizar.');",
    "    return;",
    "  }",
    "",
    "  // conta o total de unidades (não produtos únicos)",
    "  const totalItens = carrinho.reduce((acc, item) => acc + item.quantidade, 0);",
    "",
    "  // formata os itens no padrão que o servidor espera",
    "  const itensDoPedido = carrinho.map(item => ({",
    "    product_title: item.title,",
    "    quantity: item.quantidade,",
    "    unit_price: Number(item.price),",
    "  }));",
    "",
    "  const resposta = await api.post('/orders', {",
    "    total_value: valorTotal,",
    "    item_count: totalItens,",
    "    items: itensDoPedido,",
    "  });",
    "",
    "  limparCarrinho();",
    "  setSucesso(resposta.data.message || 'Pedido finalizado!');",
    "  setTimeout(() => router.replace('/meus-pedidos'), 2200);",
    "};",
  ]),
  bullet("Monta os itens no formato que o servidor espera"),
  bullet("O servidor calcula o desconto de 10% se totalItens >= 10"),
  bullet("Após sucesso: limpa o carrinho, exibe banner verde e redireciona"),
  separador(),
);

// 12. MEUS PEDIDOS
sections.push(
  titulo("12. Tela: Meus Pedidos (meus-pedidos.tsx)"),
  paragrafo("Lista todos os pedidos do cliente com status, data, quantidade de itens e valor total."),
  espaco(),
  ...blocoCode([
    "const STATUS_LABELS = {",
    "  preparing: { texto: 'Em Produção', cor: '#F59E0B' },",
    "  completed:  { texto: 'Concluído',   cor: '#10B981' },",
    "  cancelled:  { texto: 'Cancelado',   cor: '#EF4444' },",
    "  pending:    { texto: 'Pendente',    cor: '#6B7280' },",
    "};",
    "",
    "// badge colorido com o status:",
    "const status = STATUS_LABELS[item.status] ?? { texto: item.status, cor: '#6B7280' };",
    "<View style={[styles.badge, { backgroundColor: status.cor + '22' }]}>",
    "  <Text style={[styles.badgeTexto, { color: status.cor }]}>{status.texto}</Text>",
    "</View>",
    "",
    "// número do pedido por usuário (não ID global do banco):",
    "<Text>#{item.user_order_number ?? item.id}</Text>",
    "",
    "// ao tocar, vai para os detalhes:",
    "<TouchableOpacity",
    "  onPress={() => router.push({ pathname: '/detalhes-pedido', params: { id: item.id } })}",
    ">",
  ]),
  paragrafo("O status.cor + '22' adiciona '22' ao código hex da cor, criando uma versão transparente (22 = ~13% de opacidade em hex). Isso cria o fundo levemente colorido do badge sem precisar de uma biblioteca externa."),
  separador(),
);

// 13. DETALHES DO PEDIDO
sections.push(
  titulo("13. Tela: Detalhes do Pedido (detalhes-pedido.tsx)"),
  paragrafo("Mostra informações completas: número, data, status, timeline de progresso, lista de itens e resumo do pedido."),
  espaco(),

  subtitulo("Receber parâmetro de navegação:"),
  ...blocoCode([
    "// o id vem como parâmetro da rota:",
    "const { id } = useLocalSearchParams<{ id: string }>();",
    "",
    "// busca os dados do pedido específico:",
    "const response = await api.get(`/orders/${id}`);",
    "setPedido(response.data);",
  ]),
  espaco(),

  subtitulo("Timeline de progresso visual:"),
  ...blocoCode([
    "const TIMELINE = ['pending', 'preparing', 'completed'];",
    "",
    "// descobre a posição atual do pedido na timeline",
    "const statusIdx = TIMELINE.indexOf(statusAtual);",
    "",
    "{TIMELINE.map((st, idx) => {",
    "  const ativo = idx <= statusIdx; // passos anteriores = coloridos",
    "  return (",
    "    <View key={st} style={styles.timelineItem}>",
    "      {/* linha conectando os passos */}",
    "      {idx < TIMELINE.length - 1 && (",
    "        <View style={[",
    "          styles.timelineLinha,",
    "          { backgroundColor: idx < statusIdx ? '#9810FA' : colors.border }",
    "        ]} />",
    "      )}",
    "      {/* círculo do passo */}",
    "      <View style={[",
    "        styles.timelinePonto,",
    "        ativo ? { backgroundColor: '#9810FA' } : { borderColor: colors.border }",
    "      ]}>",
    "        {ativo && <Ionicons name={si.icone} size={13} color='white' />}",
    "      </View>",
    "      <Text>{si.texto}</Text>",
    "    </View>",
    "  );",
    "})}",
  ]),
  espaco(),

  subtitulo("Desconto automático:"),
  ...blocoCode([
    "{pedido.item_count >= 10 && (",
    "  <View style={styles.descontoBadge}>",
    "    <Ionicons name='pricetag-outline' color='#10B981' />",
    "    <Text>Desconto de 10% aplicado (10+ itens)</Text>",
    "  </View>",
    ")}",
  ]),
  separador(),
);

// 14. NOVO ORÇAMENTO
sections.push(
  titulo("14. Tela: Novo Orçamento (novo-orcamento.tsx)"),
  paragrafo("Permite ao cliente solicitar impressão de uma peça personalizada. Seleciona material, tamanho, adiciona foto e informa WhatsApp."),
  espaco(),

  subtitulo("14.1 Cálculo automático do preço"),
  ...blocoCode([
    "const PRECO_POR_GRAMA = { PLA: 0.50, ABS: 0.40, PETG: 0.60 };",
    "const CUSTO_POR_HORA = 5.0;",
    "",
    "const TAMANHOS = [",
    "  { label: 'Pequeno', gramas: 50,  horas: 2  },",
    "  { label: 'Médio',   gramas: 150, horas: 5  },",
    "  { label: 'Grande',  gramas: 300, horas: 10 },",
    "];",
    "",
    "function calcularPreco(material, gramas, horas) {",
    "  return gramas * PRECO_POR_GRAMA[material] + horas * CUSTO_POR_HORA;",
    "}",
    "",
    "// Exemplo: Médio (150g, 5h) com PLA:",
    "// 150 * 0.50 + 5 * 5.0 = 75 + 25 = R$ 100,00",
    "",
    "// o preço é recalculado em tempo real quando o usuário muda material ou tamanho:",
    "const precoEstimado = tamanhoSelecionado",
    "  ? calcularPreco(materialSelecionado, tamanhoSelecionado.gramas, tamanhoSelecionado.horas)",
    "  : null;",
  ]),
  espaco(),

  subtitulo("14.2 Acessar câmera e galeria"),
  ...blocoCode([
    "async function escolherImagem() {",
    "  const permissao = await ImagePicker.requestMediaLibraryPermissionsAsync();",
    "  if (permissao.status !== 'granted') {",
    "    Alert.alert('Precisamos de permissão para acessar suas fotos!');",
    "    return;",
    "  }",
    "  const resultado = await ImagePicker.launchImageLibraryAsync({",
    "    mediaTypes: ['images'],",
    "    allowsEditing: true,   // usuário pode recortar",
    "    aspect: [4, 3],        // proporção 4:3",
    "    quality: 0.9,          // 90% de qualidade",
    "  });",
    "  if (!resultado.canceled) setImagem(resultado.assets[0].uri);",
    "}",
    "",
    "async function tirarFoto() {",
    "  const permissao = await ImagePicker.requestCameraPermissionsAsync();",
    "  // ... mesma lógica com launchCameraAsync()",
    "}",
  ]),
  espaco(),

  subtitulo("14.3 Envio via FormData (arquivo + dados)"),
  ...blocoCode([
    "const pacote = new FormData();",
    "",
    "// diferença entre celular e web:",
    "if (Platform.OS === 'web') {",
    "  const resp = await fetch(imagem);",
    "  const blob = await resp.blob();",
    "  pacote.append('file', blob, 'orcamento.jpg');",
    "} else {",
    "  const nome = imagem.split('/').pop() ?? 'orcamento.jpg';",
    "  const ext = nome.split('.').pop();",
    "  pacote.append('file', { uri: imagem, name: nome, type: `image/${ext}` });",
    "}",
    "",
    "pacote.append('material', materialSelecionado);",
    "pacote.append('estimated_grams', String(tamanhoSelecionado.gramas));",
    "pacote.append('calculated_price', String(preco.toFixed(2)));",
    "pacote.append('phone', whatsapp.trim());",
    "",
    "await api.post('/orcamentos', pacote, {",
    "  headers: { 'Content-Type': 'multipart/form-data' },",
    "});",
  ]),
  paragrafo("FormData é o formato padrão para enviar arquivos em HTTP. No celular, o arquivo é referenciado por URI local. Na web, precisa ser convertido para Blob primeiro. O header Content-Type: multipart/form-data instrui o servidor a processar o pacote como arquivo."),
  separador(),
);

// 15. MEUS ORÇAMENTOS
sections.push(
  titulo("15. Tela: Meus Orçamentos (meus-orcamentos.tsx)"),
  paragrafo("Tela dedicada para o cliente ver todos os seus orçamentos com status (Em Avaliação, Aprovado, Rejeitado) e excluir os pendentes."),
  espaco(),
  ...blocoCode([
    "async function buscar() {",
    "  const resposta = await api.get(`/orcamentos/${user?.id}`);",
    "  // filtra orçamentos que viraram pedido — esses não aparecem mais aqui",
    "  setOrcamentos(resposta.data.filter(o => o.status !== 'ordered'));",
    "}",
    "",
    "function badgeStatus(status) {",
    "  if (status === 'approved') return { label: '✓ Aprovado',    bg: '#d1e7dd', color: '#146c43' }",
    "  if (status === 'rejected') return { label: '✗ Rejeitado',   bg: '#f8d7da', color: '#842029' }",
    "  return                           { label: 'Em Avaliação',   bg: '#fff3cd', color: '#664d03' }",
    "}",
    "",
    "// lixeira visível APENAS em orçamentos pendentes:",
    "{item.status === 'pending' && (",
    "  <TouchableOpacity onPress={() => remover(item.id)}>",
    "    <Ionicons name='trash-outline' color='#EF4444' />",
    "  </TouchableOpacity>",
    ")}",
  ]),
  espaco(),
  subtitulo("Exclusão segura:"),
  ...blocoCode([
    "async function remover(id) {",
    "  Alert.alert('Remover orçamento', 'Essa ação não pode ser desfeita.', [",
    "    { text: 'Cancelar', style: 'cancel' },",
    "    { text: 'Remover', style: 'destructive', onPress: async () => {",
    "      await api.delete(`/quotes/${id}`);",
    "      setOrcamentos(prev => prev.filter(o => o.id !== id));",
    "    }},",
    "  ]);",
    "}",
    "",
    "// No servidor: DELETE /quotes/:id verifica 3 condições:",
    "// 1. o orçamento existe",
    "// 2. pertence ao usuário logado (user_id = req.userId)",
    "// 3. status = 'pending' (não pode excluir aprovado/rejeitado)",
  ]),
  separador(),
);

// 16. PERFIL
sections.push(
  titulo("16. Tela: Perfil do Usuário (perfil.tsx)"),
  paragrafo("Tela com informações do usuário, acesso a Meus Pedidos e Meus Orçamentos, toggle de tema, suporte e logout."),
  espaco(),
  ...blocoCode([
    "const { user, signOut } = useContext(AuthContext);",
    "const { isDark, toggleTheme, colors } = useTheme();",
    "",
    "// Avatar com a primeira letra do nome:",
    "<View style={styles.avatarBox}>",
    "  <Text style={styles.avatarLetra}>",
    "    {(user?.name ?? 'U').charAt(0).toUpperCase()}",
    "  </Text>",
    "</View>",
    "",
    "// Badge de role:",
    "function nomeRole(role) {",
    "  if (role === 'admin') return 'Admin'",
    "  if (role === 'superadmin') return 'Superadmin'",
    "  return 'Usuário'",
    "}",
    "",
    "// Navegação para Meus Pedidos:",
    "<TouchableOpacity onPress={() => router.push('/(app)/meus-pedidos')}>",
    "  <Ionicons name='receipt-outline' color='#9810FA' />",
    "  <Text>Meus Pedidos</Text>",
    "</TouchableOpacity>",
    "",
    "// Navegação para Meus Orçamentos:",
    "<TouchableOpacity onPress={() => router.push('/(screens)/meus-orcamentos')}>",
    "  <Ionicons name='cube-outline' color='#9810FA' />",
    "  <Text>Meus Orçamentos</Text>",
    "</TouchableOpacity>",
    "",
    "// Switch de tema claro/escuro:",
    "<Switch",
    "  value={isDark}",
    "  onValueChange={toggleTheme}",
    "  trackColor={{ false: '#E0E0E0', true: '#C4B5FD' }}",
    "  thumbColor={isDark ? '#9810FA' : '#FFF'}",
    "/>",
    "",
    "// Logout com delay (evita 'flash' na tela durante transição):",
    "function realizarLogout() {",
    "  router.replace('/login');",
    "  setTimeout(() => signOut(), 300);",
    "}",
  ]),
  separador(),
);

// 17. ADMIN DASHBOARD
sections.push(
  titulo("17. Painel Admin — Dashboard (dashboard.tsx)"),
  paragrafo("Primeira tela do painel administrativo. Exibe métricas gerais: faturamento total, número de pedidos, orçamentos pendentes e produtos cadastrados."),
  espaco(),
  ...blocoCode([
    "// No servidor, o dashboard faz 3 consultas simultâneas:",
    "const [revenueResult, quotesResult, productsResult] = await Promise.all([",
    "  db.query('SELECT COUNT(id) AS total_pedidos, COALESCE(SUM(total_value),0) AS faturamento FROM orders'),",
    "  db.query(\"SELECT COUNT(id) AS pendentes FROM quotes WHERE status = 'pending'\"),",
    "  db.query('SELECT COUNT(id) AS total FROM products'),",
    "]);",
    "",
    "// Promise.all() executa as 3 queries AO MESMO TEMPO",
    "// Tempo total ≈ tempo da query mais lenta (não soma dos 3)",
    "",
    "// No app, cada card de métrica:",
    "<View style={styles.metricaCard}>",
    "  <Text style={styles.metricaValor}>",
    "    R$ {dashboard.faturamento_total.toFixed(2)}",
    "  </Text>",
    "  <Text style={styles.metricaLabel}>Faturamento Total</Text>",
    "</View>",
  ]),
  separador(),
);

// 18. ADMIN PRODUTOS
sections.push(
  titulo("18. Painel Admin — Produtos (admin/produtos.tsx)"),
  paragrafo("CRUD completo de produtos. Adicionar novos, editar existentes, remover do catálogo. Inclui busca por nome e filtro por categoria."),
  espaco(),

  subtitulo("18.1 Modal reutilizável para criar e editar"),
  ...blocoCode([
    "// estado para controlar o modal:",
    "const [modalAberto, setModalAberto] = useState(false);",
    "const [editando, setEditando] = useState<Produto | null>(null);",
    "const [form, setForm] = useState({ title: '', price: '', stock: '', ... });",
    "",
    "// abrir para editar:",
    "function abrirEditar(produto) {",
    "  setEditando(produto);",
    "  setForm({",
    "    title: produto.title,",
    "    price: String(produto.price),",
    "    stock: String(produto.stock),",
    "    // ...outros campos",
    "  });",
    "  setModalAberto(true);",
    "}",
    "",
    "// abrir para criar (sem editar):",
    "function abrirCriar() {",
    "  setEditando(null);  // null = modo criação",
    "  setForm({ title: '', price: '', stock: '', ... });",
    "  setModalAberto(true);",
    "}",
    "",
    "// ao salvar:",
    "async function salvar() {",
    "  if (editando) {",
    "    await api.put(`/products/${editando.id}`, form);",
    "    // atualiza lista local sem nova requisição:",
    "    setProdutos(prev => prev.map(p =>",
    "      p.id === editando.id ? { ...p, ...form } : p",
    "    ));",
    "  } else {",
    "    const resposta = await api.post('/products', form);",
    "    setProdutos(prev => [resposta.data.product, ...prev]);",
    "  }",
    "  setModalAberto(false);",
    "}",
  ]),
  espaco(),

  subtitulo("18.2 Excluir produto com confirmação"),
  ...blocoCode([
    "async function excluir(id) {",
    "  Alert.alert('Remover produto', 'Esta ação não pode ser desfeita.', [",
    "    { text: 'Cancelar', style: 'cancel' },",
    "    { text: 'Remover', style: 'destructive', onPress: async () => {",
    "      await api.delete(`/products/${id}`);",
    "      setProdutos(prev => prev.filter(p => p.id !== id));",
    "    }},",
    "  ]);",
    "}",
  ]),
  separador(),
);

// 19. ADMIN ORÇAMENTOS
sections.push(
  titulo("19. Painel Admin — Orçamentos (admin/orcamentos.tsx)"),
  paragrafo("Lista TODOS os orçamentos (pendentes, aprovados e rejeitados). O admin pode aprovar ou rejeitar os pendentes."),
  espaco(),
  ...blocoCode([
    "// Rota no servidor que retorna todos os orçamentos com nome do cliente:",
    "SELECT q.*, u.name AS user_name",
    "FROM quotes q",
    "LEFT JOIN users u ON u.id = q.user_id",
    "ORDER BY q.created_at DESC",
    "",
    "// LEFT JOIN: para cada orçamento, busca o nome do usuário",
    "// Se o usuário foi deletado, ainda mostra o orçamento (LEFT = não exige match)",
    "",
    "// Ícones de status nos cards:",
    "{item.status === 'approved' && <Ionicons name='checkmark-circle' color='#16A34A' />}",
    "{item.status === 'rejected' && <Ionicons name='close-circle' color='#DC2626' />}",
    "{item.status === 'pending'  && <Ionicons name='chevron-forward' color={colors.subtext} />}",
    "",
    "// Botões de ação (só aparecem para orçamentos pendentes):",
    "{item.status === 'pending' && (",
    "  <>",
    "    <TouchableOpacity onPress={() => atualizarStatus(item.id, 'approved')}>",
    "      <Text>Aprovar</Text>",
    "    </TouchableOpacity>",
    "    <TouchableOpacity onPress={() => atualizarStatus(item.id, 'rejected')}>",
    "      <Text>Rejeitar</Text>",
    "    </TouchableOpacity>",
    "  </>",
    ")}",
    "",
    "// Contador no cabeçalho:",
    "<Text>{pendentes} pendente(s)  ·  {total} total</Text>",
  ]),
  separador(),
);

// 20. ADMIN PEDIDOS
sections.push(
  titulo("20. Painel Admin — Pedidos (admin/pedidos.tsx)"),
  paragrafo("Lista todos os pedidos de todos os clientes. Admin pode ver detalhes e atualizar o status (Pendente → Em Produção → Concluído ou Cancelado)."),
  espaco(),
  ...blocoCode([
    "// Rota no servidor com numeração por usuário:",
    "SELECT o.*,",
    "       u.name AS user_name,",
    "       ROW_NUMBER() OVER (PARTITION BY o.user_id ORDER BY o.created_at)",
    "         AS user_order_number",
    "FROM orders o",
    "LEFT JOIN users u ON u.id = o.user_id",
    "ORDER BY o.created_at DESC",
    "",
    "// ROW_NUMBER() OVER (PARTITION BY user_id):",
    "// Numera os pedidos de cada usuário independentemente.",
    "// Pedido #1 do usuário A = o primeiro pedido que o usuário A fez.",
    "// Mesmo que outros usuários tenham pedidos com IDs maiores no banco,",
    "// a numeração de cada usuário começa do 1.",
  ]),
  separador(),
);

// 21. NAVEGAÇÃO
sections.push(
  titulo("21. Navegação — Expo Router e Layouts"),
  paragrafo("O Expo Router usa a estrutura de pastas para definir rotas automaticamente. Arquivos _layout.tsx controlam como as telas dentro de uma pasta se organizam."),
  espaco(),

  subtitulo("Layout raiz (_layout.tsx principal)"),
  ...blocoCode([
    "export default function RootLayout() {",
    "  const [fontsLoaded] = useFonts({ Inter_400Regular, Inter_700Bold });",
    "  if (!fontsLoaded) return null; // aguarda as fontes carregarem",
    "",
    "  return (",
    "    <ThemeProvider>      {/* disponibiliza cores e tema para todo o app */}",
    "      <AuthProvider>     {/* disponibiliza user e token para todo o app */}",
    "        <Slot />         {/* renderiza a tela atual aqui */}",
    "      </AuthProvider>",
    "    </ThemeProvider>",
    "  );",
    "}",
  ]),
  espaco(),

  subtitulo("Proteção de rotas por grupo"),
  ...blocoCode([
    "// (app)/_layout.tsx — protege as telas do cliente:",
    "if (isLoading) return null;",
    "if (!user) return <Redirect href='/login' />;",
    "",
    "return (",
    "  <CartProvider>   // carrinho disponível apenas para usuários",
    "    <Tabs>         // tab bar com 4 abas",
    "      <Tabs.Screen name='home' options={{ title: 'Loja' }} />",
    "      <Tabs.Screen name='carrinho' options={{ title: 'Carrinho' }} />",
    "      <Tabs.Screen name='meus-pedidos' options={{ title: 'Pedidos' }} />",
    "      <Tabs.Screen name='perfil' options={{ title: 'Perfil' }} />",
    "    </Tabs>",
    "  </CartProvider>",
    ");",
    "",
    "// (admin)/_layout.tsx — protege as telas do admin:",
    "if (!user) return <Redirect href='/login' />;",
    "if (user.role === 'user') return <Redirect href='/home' />;",
    "",
    "// Itens do menu visíveis apenas para admin/superadmin:",
    "<Tabs.Screen",
    "  name='produtos'",
    "  options={{ href: isAdmin ? undefined : null }}  // null = esconde da tab bar",
    "/>",
  ]),
  espaco(),

  subtitulo("Grupos de telas"),
  paragrafo("Os parênteses nos nomes de pastas (como (app), (admin), (screens)) criam grupos no Expo Router. Grupos não adicionam segmentos à URL — a rota /(app)/home é acessada como /home, não como /(app)/home."),
  paragrafo("Isso permite ter comportamentos diferentes por grupo (layouts e proteções diferentes) sem criar URLs confusas."),
  separador(),
);

// 22. FLUXOS
sections.push(
  titulo("22. Fluxos Completos do Usuário"),
  espaco(),

  subtitulo("Fluxo 1: Comprar um produto"),
  bullet("1. Cliente abre o app → vai para aba Loja"),
  bullet("2. Navega pelo catálogo, busca por nome ou filtra por categoria"),
  bullet("3. Toca no card do produto → Modal com detalhes abre"),
  bullet("4. Seleciona o material de impressão (PLA, ABS ou PETG)"),
  bullet("5. Toca em 'Adicionar ao Carrinho' → modal fecha"),
  bullet("6. Vai para a aba Carrinho"),
  bullet("7. Ajusta quantidades com + e −, remove itens se quiser"),
  bullet("8. Toca em 'Finalizar Pedido'"),
  bullet("9. App calcula total e envia para POST /orders"),
  bullet("10. Se 10+ itens, servidor aplica 10% de desconto automaticamente"),
  bullet("11. Pedido criado com status 'preparing' (Em Produção)"),
  bullet("12. App limpa carrinho e redireciona para Meus Pedidos"),
  espaco(),

  subtitulo("Fluxo 2: Solicitar orçamento personalizado"),
  bullet("1. Cliente toca no banner 'Tem uma peça para imprimir?' na Home"),
  bullet("2. Tela Novo Orçamento abre"),
  bullet("3. Adiciona foto da peça (escolhe da galeria ou tira foto)"),
  bullet("4. Seleciona o material (PLA, ABS ou PETG)"),
  bullet("5. Seleciona o tamanho aproximado (Pequeno, Médio ou Grande)"),
  bullet("6. Preço estimado é calculado e exibido em tempo real"),
  bullet("7. Informa número de WhatsApp para contato"),
  bullet("8. Toca em 'Solicitar Orçamento'"),
  bullet("9. Foto vai para o Supabase Storage, dados vão para o banco"),
  bullet("10. Admin recebe notificação e vê o orçamento no painel"),
  bullet("11. Admin aprova ou rejeita"),
  bullet("12. Cliente vê o status em Perfil → Meus Orçamentos"),
  espaco(),

  subtitulo("Fluxo 3: Admin gerenciar produtos"),
  bullet("1. Admin acessa aba Produtos no painel"),
  bullet("2. Vê lista de todos os produtos com busca e filtro"),
  bullet("3. Toca em '+ Novo Produto' → Modal de criação abre"),
  bullet("4. Preenche: título, preço, estoque, URL da imagem, categoria, descrição"),
  bullet("5. Salva → produto aparece na loja imediatamente"),
  bullet("6. Para editar: toca no lápis ao lado do produto"),
  bullet("7. Para remover: toca na lixeira → confirma → produto desaparece"),
  separador(),
);

// 23. SEGURANÇA
sections.push(
  titulo("23. Segurança"),
  espaco(),

  subtitulo("Proteção de senhas com bcrypt"),
  paragrafo("As senhas nunca são salvas como texto no banco de dados. O bcrypt usa uma função de hash unidirecional com 'salt' (sequência aleatória): mesmo que dois usuários tenham a mesma senha, os hashes gerados são diferentes. Não existe função de 'reverter' o hash para obter a senha original."),
  espaco(),

  subtitulo("Autenticação com JWT"),
  paragrafo("Após o login, o servidor gera um JWT (JSON Web Token) contendo o ID e role do usuário, assinado com uma chave secreta que só o servidor conhece. O app guarda esse token no AsyncStorage e o envia em cada requisição. O servidor verifica a assinatura sem precisar consultar o banco — se a assinatura for válida, o token é confiável."),
  espaco(),

  subtitulo("Proteção de rotas no servidor"),
  ...blocoCode([
    "Rotas públicas (sem autenticação):",
    "  GET  /products    ← qualquer um pode ver produtos",
    "  POST /login       ← qualquer um pode tentar fazer login",
    "  POST /register    ← qualquer um pode se cadastrar",
    "",
    "Rotas que exigem token JWT:",
    "  POST /orders         ← verificarToken",
    "  GET  /orders/me      ← verificarToken",
    "  GET  /orcamentos/:id ← verificarToken",
    "  DELETE /quotes/:id   ← verificarToken",
    "",
    "Rotas que exigem token + role admin:",
    "  GET  /dashboard             ← verificarToken + verificarAdmin",
    "  GET  /admin/orcamentos      ← verificarToken + verificarAdmin",
    "  PUT  /quotes/:id/status     ← verificarToken + verificarAdmin",
    "  POST /products              ← verificarToken + verificarAdmin",
    "  PUT  /products/:id          ← verificarToken + verificarAdmin",
    "  DELETE /products/:id        ← verificarToken + verificarAdmin",
  ]),
  espaco(),

  subtitulo("Exclusão de orçamentos com verificação dupla"),
  ...blocoCode([
    "// DELETE /quotes/:id no servidor:",
    "DELETE FROM quotes",
    "WHERE id = $1",
    "  AND user_id = $2          ← o orçamento deve pertencer a este usuário",
    "  AND status = 'pending'    ← só pode excluir se ainda estiver pendente",
    "RETURNING id",
    "",
    "// Se o result.rowCount === 0: o DELETE não afetou nenhuma linha",
    "// → o orçamento não existe, não pertence ao usuário, ou já foi decidido",
    "// → retorna erro 404",
  ]),
  paragrafo("Mesmo que alguém descubra o ID de um orçamento de outro usuário, não conseguirá deletá-lo porque a condição user_id = req.userId falhará. Isso é chamado de controle de acesso a nível de objeto."),
  separador(),
);

// Rodapé
sections.push(
  espaco(),
  new Paragraph({
    children: [new TextRun({ text: "Trecos3D  —  Documentação Técnica v1.0  —  2025", size: 18, color: "888888" })],
    alignment: AlignmentType.CENTER,
    spacing: { before: 400 },
  }),
);

// Gerar o arquivo
const doc = new Document({
  styles: {
    default: {
      heading1: {
        run: { bold: true, size: 32, color: "9810FA" },
        paragraph: { spacing: { before: 400, after: 200 } },
      },
      heading2: {
        run: { bold: true, size: 26, color: "1A1A1A" },
        paragraph: { spacing: { before: 300, after: 120 } },
      },
    },
  },
  sections: [{ children: sections }],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync("Trecos3D_Documentacao.docx", buffer);
  console.log("✅ Trecos3D_Documentacao.docx gerado com sucesso!");
  console.log("📄 Salvo em: C:\\dev\\Trecos3D\\Trecos3D_Documentacao.docx");
});
